/**
 * Generated by Supabase CLI:
 *   npm run gen:types
 * which runs:
 *   supabase gen types typescript --local > src/data/database.types.ts
 *
 * Until then, this is a permissive placeholder. Regenerate before the first
 * feature port — the DAL relies on row/insert/update types for type-safety
 * on every query.
 */

// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type Database = any;
